import type { Metadata } from "next";
import { ThemeProvider } from "@/src/assets/theme-provider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/src/components/Header";
import { FaviconManager } from "@/src/assets/favicon";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Data To Chart",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
			suppressHydrationWarning
		>
			<body className="min-h-full flex flex-col">
				<ThemeProvider
					themes={["light", "dark", "cream"]}
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<FaviconManager />
					<Header />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
